//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 

namespace MSAddonLib.Domain.AssetFiles
{

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("mscope.things.BodyPart", Namespace = "", IsNullable = false)]
    public partial class BodyPart
    {
        // mscopethingsBodyPart {

        private mscopethingsBodyPartPartsCovered partsCoveredField;

        private string nameField;

        private string descriptionField;

        private byte slotField;

        private string[] tagsField;

        private string[] meshesField;

        private mscopethingsBodyPartEntry[] materialsField;

        private mscopethingsBodyPartBindings bindingsField;

        /// <comentarios/>
        public mscopethingsBodyPartPartsCovered partsCovered
        {
            get { return this.partsCoveredField; }
            set { this.partsCoveredField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <comentarios/>
        public byte slot
        {
            get { return this.slotField; }
            set { this.slotField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] tags
        {
            get { return this.tagsField; }
            set { this.tagsField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] meshes
        {
            get { return this.meshesField; }
            set { this.meshesField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        public mscopethingsBodyPartEntry[] materials
        {
            get { return this.materialsField; }
            set { this.materialsField = value; }
        }

        /// <comentarios/>
        public mscopethingsBodyPartBindings bindings
        {
            get { return this.bindingsField; }
            set { this.bindingsField = value; }
        }


        /// <summary>
        /// Creates a BodyPart instance from an existent description file
        /// </summary>
        /// <param name="pFilename">Path to the bodypart description file</param>
        /// <param name="pErrorText">Text of error, if any</param>
        /// <returns>Bodypart instance, or null if error</returns>
        public static BodyPart Load(string pFilename, out string pErrorText)
        {
            pErrorText = null;
            if (!File.Exists(pFilename))
            {
                pErrorText = "BodyPart.Load(): File not found";
                return null;
            }

            BodyPart bodyPart = new BodyPart();

            try
            {
                XmlSerializer serializer = new XmlSerializer(bodyPart.GetType());
                using (StreamReader reader = new StreamReader(pFilename))
                {
                    bodyPart = (BodyPart)serializer.Deserialize(reader);
                    reader.Close();
                }
            }
            catch (Exception exception)
            {
                pErrorText = $"EXCEPTION while deserializing BodyPart: {exception.Message} - {exception.InnerException?.Message}";
                bodyPart = null;
            }

            return bodyPart;
        }




        /// <summary>
        /// Creates a BodyPart instance from a XML string
        /// </summary>
        /// <param name="pText">XML string</param>
        /// <param name="pErrorText">Text of error, if any</param>
        /// <returns>BodyPart instance, or null if error</returns>
        public static BodyPart LoadFromString(string pText, out string pErrorText)
        {
            pErrorText = null;
            if (string.IsNullOrEmpty(pText = pText?.Trim()))
            {
                pErrorText = "BodyPart.LoadFromString(): No input text";
                return null;
            }

            AssetFiles.BodyPart bodyPart = new BodyPart();

            try
            {
                XmlSerializer serializer = new XmlSerializer(bodyPart.GetType());
                using (TextReader reader = new StringReader(pText))
                {
                    bodyPart = (BodyPart)serializer.Deserialize(reader);
                    reader.Close();
                }
            }
            catch (Exception exception)
            {
                pErrorText = $"EXCEPTION while deserializing BodyPart: {exception.Message} - {exception.InnerException?.Message}";
                bodyPart = null;
            }

            return bodyPart;
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPartPartsCovered
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get { return this.enumtypeField; }
            set { this.enumtypeField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPartEntry
    {
        // Originally byte - had to change to ulong because of unexpectedly high values in some props by Writerly
        private ulong intField;

        private mscopethingsBodyPartEntryList listField;

        /// <comentarios/>
        public ulong @int
        {
            get { return this.intField; }
            set { this.intField = value; }
        }

        /// <comentarios/>
        public mscopethingsBodyPartEntryList list
        {
            get { return this.listField; }
            set { this.listField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPartEntryList
    {

        private mscopethingsBodyPartEntryListMaterial materialField;

        /// <comentarios/>
        public mscopethingsBodyPartEntryListMaterial material
        {
            get { return this.materialField; }
            set { this.materialField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPartEntryListMaterial
    {

        private string nameField;

        private string ambientColorField;

        private string diffuseColorField;

        private string emissiveColorField;

        private string specularColorField;

        private decimal shininessField;

        private string[][] mapsField;

        private string[] flagsField;

        private object parametersField;

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public string ambientColor
        {
            get { return this.ambientColorField; }
            set { this.ambientColorField = value; }
        }

        /// <comentarios/>
        public string diffuseColor
        {
            get { return this.diffuseColorField; }
            set { this.diffuseColorField = value; }
        }

        /// <comentarios/>
        public string emissiveColor
        {
            get { return this.emissiveColorField; }
            set { this.emissiveColorField = value; }
        }

        /// <comentarios/>
        public string specularColor
        {
            get { return this.specularColorField; }
            set { this.specularColorField = value; }
        }

        /// <comentarios/>
        public decimal shininess
        {
            get { return this.shininessField; }
            set { this.shininessField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false, NestingLevel = 1)]
        public string[][] maps
        {
            get { return this.mapsField; }
            set { this.mapsField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] flags
        {
            get { return this.flagsField; }
            set { this.flagsField = value; }
        }

        /// <comentarios/>
        public object parameters
        {
            get { return this.parametersField; }
            set { this.parametersField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPartBindings
    {

        private object boneBindingsField;

        /// <comentarios/>
        public object boneBindings
        {
            get { return this.boneBindingsField; }
            set { this.boneBindingsField = value; }
        }
    }

}