//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 

namespace MSAddonLib.Domain.AssetFiles
{


    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("mscope.things.BodyPart_-MorphPart", Namespace = "", IsNullable = false)]
    public partial class BodyPartMorph
    {
        // mscopethingsBodyPart_MorphPart {

        private string baseMeshField;

        private string baseNormalMapField;

        private mscopethingsBodyPart_MorphPartMscopethingsBodyPart_MorphTarget[] morphTargetsField;

        private mscopethingsBodyPart_MorphPartMaterial[] decalsField;

        private mscopethingsBodyPart_MorphPartPartsCovered partsCoveredField;

        private string soundTagField;

        private string nameField;

        private string descriptionField;

        private byte slotField;

        private string[] tagsField;

        private string[] meshesField;

        private mscopethingsBodyPart_MorphPartEntry[] materialsField;

        private mscopethingsBodyPart_MorphPartBindings bindingsField;

        /// <comentarios/>
        public string baseMesh
        {
            get { return this.baseMeshField; }
            set { this.baseMeshField = value; }
        }

        /// <comentarios/>
        public string baseNormalMap
        {
            get { return this.baseNormalMapField; }
            set { this.baseNormalMapField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mscope.things.BodyPart_-MorphTarget", IsNullable = false)]
        public mscopethingsBodyPart_MorphPartMscopethingsBodyPart_MorphTarget[] morphTargets
        {
            get { return this.morphTargetsField; }
            set { this.morphTargetsField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("material", IsNullable = false)]
        public mscopethingsBodyPart_MorphPartMaterial[] decals
        {
            get { return this.decalsField; }
            set { this.decalsField = value; }
        }

        /// <comentarios/>
        public mscopethingsBodyPart_MorphPartPartsCovered partsCovered
        {
            get { return this.partsCoveredField; }
            set { this.partsCoveredField = value; }
        }

        /// <comentarios/>
        public string soundTag
        {
            get { return this.soundTagField; }
            set { this.soundTagField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public string description
        {
            get { return this.descriptionField; }
            set { this.descriptionField = value; }
        }

        /// <comentarios/>
        public byte slot
        {
            get { return this.slotField; }
            set { this.slotField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] tags
        {
            get { return this.tagsField; }
            set { this.tagsField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] meshes
        {
            get { return this.meshesField; }
            set { this.meshesField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        public mscopethingsBodyPart_MorphPartEntry[] materials
        {
            get { return this.materialsField; }
            set { this.materialsField = value; }
        }

        /// <comentarios/>
        public mscopethingsBodyPart_MorphPartBindings bindings
        {
            get { return this.bindingsField; }
            set { this.bindingsField = value; }
        }


        /// <summary>
        /// Creates a BodyPartMorph instance from an existent description file
        /// </summary>
        /// <param name="pFilename">Path to the bodypart description file</param>
        /// <param name="pErrorText">Text of error, if any</param>
        /// <returns>BodyPartMorph instance, or null if error</returns>
        public static BodyPartMorph Load(string pFilename, out string pErrorText)
        {
            pErrorText = null;
            if (!File.Exists(pFilename))
            {
                pErrorText = "BodyPartMorph.Load(): File not found";
                return null;
            }

            BodyPartMorph bodyPart = new BodyPartMorph();

            try
            {
                XmlSerializer serializer = new XmlSerializer(bodyPart.GetType());
                using (StreamReader reader = new StreamReader(pFilename))
                {
                    bodyPart = (BodyPartMorph)serializer.Deserialize(reader);
                    reader.Close();
                }
            }
            catch (Exception exception)
            {
                pErrorText = $"EXCEPTION while deserializing BodyPartMorph: {exception.Message} - {exception.InnerException?.Message}";
                bodyPart = null;
            }

            return bodyPart;
        }




        /// <summary>
        /// Creates a BodyPartMorph instance from a XML string
        /// </summary>
        /// <param name="pText">XML string</param>
        /// <param name="pErrorText">Text of error, if any</param>
        /// <returns>BodyPartMorph instance, or null if error</returns>
        public static BodyPartMorph LoadFromString(string pText, out string pErrorText)
        {
            pErrorText = null;
            if (string.IsNullOrEmpty(pText = pText?.Trim()))
            {
                pErrorText = "BodyPartMorph.LoadFromString(): No input text";
                return null;
            }

            BodyPartMorph bodyPartMorph = new BodyPartMorph();

            try
            {
                XmlSerializer serializer = new XmlSerializer(bodyPartMorph.GetType());
                using (TextReader reader = new StringReader(pText))
                {
                    bodyPartMorph = (BodyPartMorph)serializer.Deserialize(reader);
                    reader.Close();
                }
            }
            catch (Exception exception)
            {
                pErrorText = $"EXCEPTION while deserializing BodyPartMorph: {exception.Message} - {exception.InnerException?.Message}";
                bodyPartMorph = null;
            }

            return bodyPartMorph;

        }
    }

    // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartMscopethingsBodyPart_MorphTarget
    {

        private string meshField;

        private string normalMapField;

        private mscopethingsBodyPart_MorphPartMscopethingsBodyPart_MorphTargetRegion regionField;

        private string menuNameField;

        /// <comentarios/>
        public string mesh
        {
            get
            {
                return this.meshField;
            }
            set
            {
                this.meshField = value;
            }
        }

        /// <comentarios/>
        public string normalMap
        {
            get
            {
                return this.normalMapField;
            }
            set
            {
                this.normalMapField = value;
            }
        }

        /// <comentarios/>
        public mscopethingsBodyPart_MorphPartMscopethingsBodyPart_MorphTargetRegion region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <comentarios/>
        public string menuName
        {
            get
            {
                return this.menuNameField;
            }
            set
            {
                this.menuNameField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartMscopethingsBodyPart_MorphTargetRegion
    {

        private string referenceField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartMaterial
    {

        private string nameField;

        private string diffuseColorField;

        private decimal shininessField;

        private string[][] mapsField;

        private string[] flagsField;

        private string[][] parametersField;

        /// <comentarios/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <comentarios/>
        public string diffuseColor
        {
            get
            {
                return this.diffuseColorField;
            }
            set
            {
                this.diffuseColorField = value;
            }
        }

        /// <comentarios/>
        public decimal shininess
        {
            get
            {
                return this.shininessField;
            }
            set
            {
                this.shininessField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false, NestingLevel = 1)]
        public string[][] maps
        {
            get
            {
                return this.mapsField;
            }
            set
            {
                this.mapsField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false, NestingLevel = 1)]
        public string[][] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartPartsCovered
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get
            {
                return this.classField;
            }
            set
            {
                this.classField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get
            {
                return this.enumtypeField;
            }
            set
            {
                this.enumtypeField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartEntry
    {

        private byte intField;

        private mscopethingsBodyPart_MorphPartEntryMaterial[] listField;

        /// <comentarios/>
        public byte @int
        {
            get
            {
                return this.intField;
            }
            set
            {
                this.intField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("material", IsNullable = false)]
        public mscopethingsBodyPart_MorphPartEntryMaterial[] list
        {
            get
            {
                return this.listField;
            }
            set
            {
                this.listField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartEntryMaterial
    {

        private string nameField;

        private string ambientColorField;

        private string diffuseColorField;

        private string emissiveColorField;

        private string specularColorField;

        private decimal shininessField;

        private string[][] mapsField;

        private string[] flagsField;

        private mscopethingsBodyPart_MorphPartEntryMaterialEntry1[] parametersField;

        /// <comentarios/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <comentarios/>
        public string ambientColor
        {
            get
            {
                return this.ambientColorField;
            }
            set
            {
                this.ambientColorField = value;
            }
        }

        /// <comentarios/>
        public string diffuseColor
        {
            get
            {
                return this.diffuseColorField;
            }
            set
            {
                this.diffuseColorField = value;
            }
        }

        /// <comentarios/>
        public string emissiveColor
        {
            get
            {
                return this.emissiveColorField;
            }
            set
            {
                this.emissiveColorField = value;
            }
        }

        /// <comentarios/>
        public string specularColor
        {
            get
            {
                return this.specularColorField;
            }
            set
            {
                this.specularColorField = value;
            }
        }

        /// <comentarios/>
        public decimal shininess
        {
            get
            {
                return this.shininessField;
            }
            set
            {
                this.shininessField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false, NestingLevel = 1)]
        public string[][] maps
        {
            get
            {
                return this.mapsField;
            }
            set
            {
                this.mapsField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        public mscopethingsBodyPart_MorphPartEntryMaterialEntry1[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartEntryMaterialEntry1
    {

        private string[] stringField;

        private decimal floatField;

        private bool floatFieldSpecified;

        private bool booleanField;

        private bool booleanFieldSpecified;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("string")]
        public string[] @string
        {
            get
            {
                return this.stringField;
            }
            set
            {
                this.stringField = value;
            }
        }

        /// <comentarios/>
        public decimal @float
        {
            get
            {
                return this.floatField;
            }
            set
            {
                this.floatField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool floatSpecified
        {
            get
            {
                return this.floatFieldSpecified;
            }
            set
            {
                this.floatFieldSpecified = value;
            }
        }

        /// <comentarios/>
        public bool boolean
        {
            get
            {
                return this.booleanField;
            }
            set
            {
                this.booleanField = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool booleanSpecified
        {
            get
            {
                return this.booleanFieldSpecified;
            }
            set
            {
                this.booleanFieldSpecified = value;
            }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class mscopethingsBodyPart_MorphPartBindings
    {

        private object boneBindingsField;

        /// <comentarios/>
        public object boneBindings
        {
            get
            {
                return this.boneBindingsField;
            }
            set
            {
                this.boneBindingsField = value;
            }
        }
    }


    // >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

}