//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
// 

namespace MSAddonLib.Domain.AssetFiles
{

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class StateMachine
    {

        private StateMachineNameMap[] nameMapField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("NameMap")]
        public StateMachineNameMap[] NameMap
        {
            get { return this.nameMapField; }
            set { this.nameMapField = value; }
        }


        /// <summary>
        /// Creates a StateMachine instance from an existent StateMachine file
        /// </summary>
        /// <param name="pFilename">Path to the StateMachine description file</param>
        /// <param name="pErrorText">Text of error, if any</param>
        /// <returns>StateMachine instance, or null if error</returns>
        public static StateMachine Load(string pFilename, out string pErrorText)
        {
            pErrorText = null;
            if (!File.Exists(pFilename))
            {
                pErrorText = "StateMachine.Load(): File not found";
                return null;
            }

            StateMachine stateMachine = new StateMachine();

            try
            {
                XmlSerializer serializer = new XmlSerializer(stateMachine.GetType());
                using (StreamReader reader = new StreamReader(pFilename))
                {
                    stateMachine = (StateMachine)serializer.Deserialize(reader);
                    reader.Close();
                }
            }
            catch (Exception exception)
            {
                pErrorText = $"EXCEPTION while deserializing StateMachine: {exception.Message} - {exception.InnerException?.Message}";
                stateMachine = null;
            }

            return stateMachine;
        }




        /// <summary>
        /// Creates a StateMachine instance from a XML string
        /// </summary>
        /// <param name="pText">XML string</param>
        /// <param name="pErrorText">Text of error, if any</param>
        /// <returns>StateMachine instance, or null if error</returns>
        public static StateMachine LoadFromString(string pText, out string pErrorText)
        {
            pErrorText = null;
            if (string.IsNullOrEmpty(pText = pText?.Trim()))
            {
                pErrorText = "StateMachine.LoadFromString(): No input text";
                return null;
            }

            StateMachine stateMachine = new StateMachine();

            try
            {
                XmlSerializer serializer = new XmlSerializer(stateMachine.GetType());
                using (TextReader reader = new StringReader(pText))
                {
                    stateMachine = (StateMachine)serializer.Deserialize(reader);
                    reader.Close();
                }
            }
            catch (Exception exception)
            {
                pErrorText = $"EXCEPTION while deserializing StateMachine: {exception.Message} - {exception.InnerException?.Message}";
                stateMachine = null;
            }

            return stateMachine;
        }



    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMap
    {

        private object[] itemsField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("AnimTransition", typeof(StateMachineNameMapAnimTransition))]
        [System.Xml.Serialization.XmlElementAttribute("GestureTransition",
            typeof(StateMachineNameMapGestureTransition))]
        [System.Xml.Serialization.XmlElementAttribute("State", typeof(StateMachineNameMapState))]
        [System.Xml.Serialization.XmlElementAttribute("mscope.things.ai.IdleStateMachine_-1",
            typeof(StateMachineNameMapMscopethingsaiIdleStateMachine_1))]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapAnimTransition
    {

        private object[] itemsField;

        private TransitionsItemsChoiceType[] itemsElementNameField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("events", typeof(StateMachineNameMapAnimTransitionEvents))]
        [System.Xml.Serialization.XmlElementAttribute("interest", typeof(byte))]
        [System.Xml.Serialization.XmlElementAttribute("menuPath", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("name", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("nextState", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("resources", typeof(StateMachineNameMapAnimTransitionResources))]
        [System.Xml.Serialization.XmlElementAttribute("soundLevel", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("soundTime", typeof(decimal))]
        [System.Xml.Serialization.XmlElementAttribute("startState", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get { return this.itemsField; }
            set { this.itemsField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public TransitionsItemsChoiceType[] ItemsElementName
        {
            get { return this.itemsElementNameField; }
            set { this.itemsElementNameField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapAnimTransitionEvents
    {

        private StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsPropAppearEvent
            mscopethingsaitransitionsPropAppearEventField;

        private StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsFireGunEvent[]
            mscopethingsaitransitionsFireGunEventField;

        private StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsCustomEvent[]
            mscopethingsaitransitionsCustomEventField;

        private StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsAnimSoundEvent[]
            mscopethingsaitransitionsAnimSoundEventField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("mscope.things.ai.transitions.PropAppearEvent")]
        public StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsPropAppearEvent
            mscopethingsaitransitionsPropAppearEvent
        {
            get { return this.mscopethingsaitransitionsPropAppearEventField; }
            set { this.mscopethingsaitransitionsPropAppearEventField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("mscope.things.ai.transitions.FireGunEvent")]
        public StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsFireGunEvent[]
            mscopethingsaitransitionsFireGunEvent
        {
            get { return this.mscopethingsaitransitionsFireGunEventField; }
            set { this.mscopethingsaitransitionsFireGunEventField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("mscope.things.ai.transitions.CustomEvent")]
        public StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsCustomEvent[]
            mscopethingsaitransitionsCustomEvent
        {
            get { return this.mscopethingsaitransitionsCustomEventField; }
            set { this.mscopethingsaitransitionsCustomEventField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("mscope.things.ai.transitions.AnimSoundEvent")]
        public StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsAnimSoundEvent[]
            mscopethingsaitransitionsAnimSoundEvent
        {
            get { return this.mscopethingsaitransitionsAnimSoundEventField; }
            set { this.mscopethingsaitransitionsAnimSoundEventField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsPropAppearEvent
    {

        private bool isAppearField;

        private string nameField;

        private decimal timeField;

        /// <comentarios/>
        public bool isAppear
        {
            get { return this.isAppearField; }
            set { this.isAppearField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public decimal time
        {
            get { return this.timeField; }
            set { this.timeField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsFireGunEvent
    {

        private string soundField;

        private decimal volumeField;

        private string nameField;

        private decimal timeField;

        /// <comentarios/>
        public string sound
        {
            get { return this.soundField; }
            set { this.soundField = value; }
        }

        /// <comentarios/>
        public decimal volume
        {
            get { return this.volumeField; }
            set { this.volumeField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public decimal time
        {
            get { return this.timeField; }
            set { this.timeField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsCustomEvent
    {

        private string methodNameField;

        private string argStringField;

        private byte playbackFlagsField;

        private string nameField;

        private decimal timeField;

        /// <comentarios/>
        public string methodName
        {
            get { return this.methodNameField; }
            set { this.methodNameField = value; }
        }

        /// <comentarios/>
        public string argString
        {
            get { return this.argStringField; }
            set { this.argStringField = value; }
        }

        /// <comentarios/>
        public byte playbackFlags
        {
            get { return this.playbackFlagsField; }
            set { this.playbackFlagsField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public decimal time
        {
            get { return this.timeField; }
            set { this.timeField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapAnimTransitionEventsMscopethingsaitransitionsAnimSoundEvent
    {

        private string soundField;

        private decimal volumeField;

        private string nameField;

        private decimal timeField;

        /// <comentarios/>
        public string sound
        {
            get { return this.soundField; }
            set { this.soundField = value; }
        }

        /// <comentarios/>
        public decimal volume
        {
            get { return this.volumeField; }
            set { this.volumeField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public decimal time
        {
            get { return this.timeField; }
            set { this.timeField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapAnimTransitionResources
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get { return this.enumtypeField; }
            set { this.enumtypeField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum TransitionsItemsChoiceType
    {

        /// <comentarios/>
        events,

        /// <comentarios/>
        interest,

        /// <comentarios/>
        menuPath,

        /// <comentarios/>
        name,

        /// <comentarios/>
        nextState,

        /// <comentarios/>
        resources,

        /// <comentarios/>
        soundLevel,

        /// <comentarios/>
        soundTime,

        /// <comentarios/>
        startState,
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapGestureTransition
    {

        private decimal melodramaField;

        private StateMachineNameMapGestureTransitionEntry[] weightsField;

        private string[] tagsField;

        private string menuPathField;

        private string soundField;

        private decimal soundTimeField;

        private decimal soundLevelField;

        private byte interestField;

        private StateMachineNameMapGestureTransitionMscopethingsaitransitionsAnimSoundEvent[] eventsField;

        private string nameField;

        private string startStateField;

        private string nextStateField;

        private StateMachineNameMapGestureTransitionResources resourcesField;

        /// <comentarios/>
        public decimal melodrama
        {
            get { return this.melodramaField; }
            set { this.melodramaField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable = false)]
        public StateMachineNameMapGestureTransitionEntry[] weights
        {
            get { return this.weightsField; }
            set { this.weightsField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public string[] tags
        {
            get { return this.tagsField; }
            set { this.tagsField = value; }
        }

        /// <comentarios/>
        public string menuPath
        {
            get { return this.menuPathField; }
            set { this.menuPathField = value; }
        }

        /// <comentarios/>
        public string sound
        {
            get { return this.soundField; }
            set { this.soundField = value; }
        }

        /// <comentarios/>
        public decimal soundTime
        {
            get { return this.soundTimeField; }
            set { this.soundTimeField = value; }
        }

        /// <comentarios/>
        public decimal soundLevel
        {
            get { return this.soundLevelField; }
            set { this.soundLevelField = value; }
        }

        /// <comentarios/>
        public byte interest
        {
            get { return this.interestField; }
            set { this.interestField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("mscope.things.ai.transitions.AnimSoundEvent", IsNullable =
            false)]
        public StateMachineNameMapGestureTransitionMscopethingsaitransitionsAnimSoundEvent[] events
        {
            get { return this.eventsField; }
            set { this.eventsField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public string startState
        {
            get { return this.startStateField; }
            set { this.startStateField = value; }
        }

        /// <comentarios/>
        public string nextState
        {
            get { return this.nextStateField; }
            set { this.nextStateField = value; }
        }

        /// <comentarios/>
        public StateMachineNameMapGestureTransitionResources resources
        {
            get { return this.resourcesField; }
            set { this.resourcesField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapGestureTransitionEntry
    {

        private string stringField;

        private decimal floatField;

        /// <comentarios/>
        public string @string
        {
            get { return this.stringField; }
            set { this.stringField = value; }
        }

        /// <comentarios/>
        public decimal @float
        {
            get { return this.floatField; }
            set { this.floatField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapGestureTransitionMscopethingsaitransitionsAnimSoundEvent
    {

        private string soundField;

        private decimal volumeField;

        private string nameField;

        private decimal timeField;

        /// <comentarios/>
        public string sound
        {
            get { return this.soundField; }
            set { this.soundField = value; }
        }

        /// <comentarios/>
        public decimal volume
        {
            get { return this.volumeField; }
            set { this.volumeField = value; }
        }

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public decimal time
        {
            get { return this.timeField; }
            set { this.timeField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapGestureTransitionResources
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get { return this.enumtypeField; }
            set { this.enumtypeField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapState
    {

        private string nameField;

        private StateMachineNameMapStateSuperstate superstateField;

        private StateMachineNameMapStateResources resourcesField;

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public StateMachineNameMapStateSuperstate superstate
        {
            get { return this.superstateField; }
            set { this.superstateField = value; }
        }

        /// <comentarios/>
        public StateMachineNameMapStateResources resources
        {
            get { return this.resourcesField; }
            set { this.resourcesField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapStateSuperstate
    {

        private string nameField;

        private StateMachineNameMapStateSuperstateSuperstate superstateField;

        private StateMachineNameMapStateSuperstateResources resourcesField;

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public StateMachineNameMapStateSuperstateSuperstate superstate
        {
            get { return this.superstateField; }
            set { this.superstateField = value; }
        }

        /// <comentarios/>
        public StateMachineNameMapStateSuperstateResources resources
        {
            get { return this.resourcesField; }
            set { this.resourcesField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapStateSuperstateSuperstate
    {

        private string nameField;

        private StateMachineNameMapStateSuperstateSuperstateResources resourcesField;

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public StateMachineNameMapStateSuperstateSuperstateResources resources
        {
            get { return this.resourcesField; }
            set { this.resourcesField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapStateSuperstateSuperstateResources
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get { return this.enumtypeField; }
            set { this.enumtypeField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapStateSuperstateResources
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get { return this.enumtypeField; }
            set { this.enumtypeField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapStateResources
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get { return this.enumtypeField; }
            set { this.enumtypeField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapMscopethingsaiIdleStateMachine_1
    {

        private string nameField;

        private string startStateField;

        private string nextStateField;

        private StateMachineNameMapMscopethingsaiIdleStateMachine_1Resources resourcesField;

        /// <comentarios/>
        public string name
        {
            get { return this.nameField; }
            set { this.nameField = value; }
        }

        /// <comentarios/>
        public string startState
        {
            get { return this.startStateField; }
            set { this.startStateField = value; }
        }

        /// <comentarios/>
        public string nextState
        {
            get { return this.nextStateField; }
            set { this.nextStateField = value; }
        }

        /// <comentarios/>
        public StateMachineNameMapMscopethingsaiIdleStateMachine_1Resources resources
        {
            get { return this.resourcesField; }
            set { this.resourcesField = value; }
        }
    }

    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class StateMachineNameMapMscopethingsaiIdleStateMachine_1Resources
    {

        private string classField;

        private string enumtypeField;

        private string valueField;

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class
        {
            get { return this.classField; }
            set { this.classField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute("enum-type")]
        public string enumtype
        {
            get { return this.enumtypeField; }
            set { this.enumtypeField = value; }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get { return this.valueField; }
            set { this.valueField = value; }
        }
    }

}